// Generated by gencpp from file mapper/SemLabel.msg
// DO NOT EDIT!


#ifndef MAPPER_MESSAGE_SEMLABEL_H
#define MAPPER_MESSAGE_SEMLABEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mapper
{
template <class ContainerAllocator>
struct SemLabel_
{
  typedef SemLabel_<ContainerAllocator> Type;

  SemLabel_()
    : header()
    , label()
    , r()
    , g()
    , b()
    , prob()
    , lvl(0)  {
    }
  SemLabel_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , label(_alloc)
    , r(_alloc)
    , g(_alloc)
    , b(_alloc)
    , prob(_alloc)
    , lvl(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _label_type;
  _label_type label;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _r_type;
  _r_type r;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _g_type;
  _g_type g;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _b_type;
  _b_type b;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _prob_type;
  _prob_type prob;

   typedef int32_t _lvl_type;
  _lvl_type lvl;





  typedef boost::shared_ptr< ::mapper::SemLabel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mapper::SemLabel_<ContainerAllocator> const> ConstPtr;

}; // struct SemLabel_

typedef ::mapper::SemLabel_<std::allocator<void> > SemLabel;

typedef boost::shared_ptr< ::mapper::SemLabel > SemLabelPtr;
typedef boost::shared_ptr< ::mapper::SemLabel const> SemLabelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mapper::SemLabel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mapper::SemLabel_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mapper

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'mapper': ['/home/bart/ros_map/src/mapper/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mapper::SemLabel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mapper::SemLabel_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mapper::SemLabel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mapper::SemLabel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mapper::SemLabel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mapper::SemLabel_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mapper::SemLabel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0419e48e313c70a6c29f5da83e48665d";
  }

  static const char* value(const ::mapper::SemLabel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0419e48e313c70a6ULL;
  static const uint64_t static_value2 = 0xc29f5da83e48665dULL;
};

template<class ContainerAllocator>
struct DataType< ::mapper::SemLabel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mapper/SemLabel";
  }

  static const char* value(const ::mapper::SemLabel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mapper::SemLabel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
string label\n\
int32[] r\n\
int32[] g\n\
int32[] b\n\
float32[] prob\n\
int32 lvl\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::mapper::SemLabel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mapper::SemLabel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.label);
      stream.next(m.r);
      stream.next(m.g);
      stream.next(m.b);
      stream.next(m.prob);
      stream.next(m.lvl);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SemLabel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mapper::SemLabel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mapper::SemLabel_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.label);
    s << indent << "r[]" << std::endl;
    for (size_t i = 0; i < v.r.size(); ++i)
    {
      s << indent << "  r[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.r[i]);
    }
    s << indent << "g[]" << std::endl;
    for (size_t i = 0; i < v.g.size(); ++i)
    {
      s << indent << "  g[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.g[i]);
    }
    s << indent << "b[]" << std::endl;
    for (size_t i = 0; i < v.b.size(); ++i)
    {
      s << indent << "  b[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.b[i]);
    }
    s << indent << "prob[]" << std::endl;
    for (size_t i = 0; i < v.prob.size(); ++i)
    {
      s << indent << "  prob[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.prob[i]);
    }
    s << indent << "lvl: ";
    Printer<int32_t>::stream(s, indent + "  ", v.lvl);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAPPER_MESSAGE_SEMLABEL_H
